[package]
name = "ppom"
version = "0.5.0"
authors = ["prataprc <prataprc@gmail.com>"]
description = "Left Leaning Red Black index in Rust-lang"
documentation = "https://docs.rs/ppom"
homepage = "https://github.com/bnclabs/ppom"
repository = "https://github.com/bnclabs/ppom"
keywords = ["storage", "llrb", "sorting", "data-structure"]
categories = ["algorithms", "database", "data-structure"]
license = "MIT"
readme = "README.md"
edition = "2018"

[dependencies]
rand = "0.6.4"
mkit = { path = "../mkit", version = "0.2.0" }

# [badges]
# maintenance = { status = "actively-developed" }
# travis-ci = { repository = "bnclabs/ppom" }
